name = "Flywheel Gregcraft"
author = "CreepSean"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f0cab264bb5e45cee006fd4c1d074badb52b25fd29fdb8f0e2577b491b376ba"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
